name = "nyagucha-tribute"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "nyagucha-tributes"
database_id = "bedcc18c-6653-4325-9043-9d4a5ccb13ba"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "nyagucha-images"
